# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queue.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bqueue.proto\x12\x05queue\"\x14\n\x04item\x12\x0c\n\x04item\x18\x01 \x01(\t\"\x14\n\x04size\x12\x0c\n\x04size\x18\x01 \x01(\x05\"\x07\n\x05\x65mpty\"\x16\n\x06isFull\x12\x0c\n\x04\x66ull\x18\x01 \x01(\x08\x32\x9a\x01\n\x05Queue\x12#\n\x03Put\x12\x0b.queue.item\x1a\r.queue.isFull\"\x00\x12#\n\x04Peek\x12\x0c.queue.empty\x1a\x0b.queue.item\"\x00\x12\"\n\x03Pop\x12\x0c.queue.empty\x1a\x0b.queue.item\"\x00\x12#\n\x04Size\x12\x0c.queue.empty\x1a\x0b.queue.size\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEM']._serialized_start=22
  _globals['_ITEM']._serialized_end=42
  _globals['_SIZE']._serialized_start=44
  _globals['_SIZE']._serialized_end=64
  _globals['_EMPTY']._serialized_start=66
  _globals['_EMPTY']._serialized_end=73
  _globals['_ISFULL']._serialized_start=75
  _globals['_ISFULL']._serialized_end=97
  _globals['_QUEUE']._serialized_start=100
  _globals['_QUEUE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
